// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arith.proto

#ifndef PROTOBUF_arith_2eproto__INCLUDED
#define PROTOBUF_arith_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_arith_2eproto();
void protobuf_AssignDesc_arith_2eproto();
void protobuf_ShutdownFile_arith_2eproto();

class ArithRequest;
class ArithResponse;

// ===================================================================

class ArithRequest : public ::google::protobuf::Message {
 public:
  ArithRequest();
  virtual ~ArithRequest();

  ArithRequest(const ArithRequest& from);

  inline ArithRequest& operator=(const ArithRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArithRequest& default_instance();

  void Swap(ArithRequest* other);

  // implements Message ----------------------------------------------

  inline ArithRequest* New() const { return New(NULL); }

  ArithRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ArithRequest& from);
  void MergeFrom(const ArithRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArithRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 a = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // optional int32 b = 2;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.ArithRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_arith_2eproto();
  friend void protobuf_AssignDesc_arith_2eproto();
  friend void protobuf_ShutdownFile_arith_2eproto();

  void InitAsDefaultInstance();
  static ArithRequest* default_instance_;
};
// -------------------------------------------------------------------

class ArithResponse : public ::google::protobuf::Message {
 public:
  ArithResponse();
  virtual ~ArithResponse();

  ArithResponse(const ArithResponse& from);

  inline ArithResponse& operator=(const ArithResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArithResponse& default_instance();

  void Swap(ArithResponse* other);

  // implements Message ----------------------------------------------

  inline ArithResponse* New() const { return New(NULL); }

  ArithResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ArithResponse& from);
  void MergeFrom(const ArithResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArithResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 c = 1;
  void clear_c();
  static const int kCFieldNumber = 1;
  ::google::protobuf::int32 c() const;
  void set_c(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.ArithResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 c_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_arith_2eproto();
  friend void protobuf_AssignDesc_arith_2eproto();
  friend void protobuf_ShutdownFile_arith_2eproto();

  void InitAsDefaultInstance();
  static ArithResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ArithRequest

// optional int32 a = 1;
inline void ArithRequest::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 ArithRequest::a() const {
  // @@protoc_insertion_point(field_get:message.ArithRequest.a)
  return a_;
}
inline void ArithRequest::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:message.ArithRequest.a)
}

// optional int32 b = 2;
inline void ArithRequest::clear_b() {
  b_ = 0;
}
inline ::google::protobuf::int32 ArithRequest::b() const {
  // @@protoc_insertion_point(field_get:message.ArithRequest.b)
  return b_;
}
inline void ArithRequest::set_b(::google::protobuf::int32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:message.ArithRequest.b)
}

// -------------------------------------------------------------------

// ArithResponse

// optional int32 c = 1;
inline void ArithResponse::clear_c() {
  c_ = 0;
}
inline ::google::protobuf::int32 ArithResponse::c() const {
  // @@protoc_insertion_point(field_get:message.ArithResponse.c)
  return c_;
}
inline void ArithResponse::set_c(::google::protobuf::int32 value) {
  
  c_ = value;
  // @@protoc_insertion_point(field_set:message.ArithResponse.c)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_arith_2eproto__INCLUDED
